# core/compose_generator.py
# v0.6.0 — Генерация docker-compose из деплой-групп.
# Локальные группы -> docker-compose.yml
# Удалённые таргеты -> docker-compose.remote_<host>.yml + DEPLOY_REMOTE.md
# Все сервисы получают один ROS_DOMAIN_ID => DDS discovery видит топики
# между контейнерами.

import os
import re
import yaml

from core.container_config import resolved_env, netem_command, safe_group_name


class ComposeGenerator:
    def __init__(self, project_path, pkg_name, config_store):
        self.project_path = project_path
        self.pkg_name = pkg_name
        self.store = config_store

    # ------------------------------------------------------------------ #
    def generate(self, groups):
        """
        groups: {group_name: [ {'language','filename','group'}, ... ]}
        Возвращает список путей к созданным compose-файлам.
        """
        local_services = {}
        remote = {}  # host -> {service_name: service_def}

        for group_name, files in groups.items():
            gname = safe_group_name(group_name)
            cfg = self.store.get(gname)
            service = self._build_service(gname, cfg, files)
            target = cfg.get("target") or {}
            if target.get("type") == "ssh" and target.get("host"):
                remote.setdefault(target["host"], {})[f"bp_{gname}"] = service
            else:
                local_services[f"bp_{gname}"] = service

        written = []
        if local_services:
            written.append(self._write_compose("docker-compose.yml", local_services))
        for host, services in remote.items():
            safe_host = re.sub(r"[^a-zA-Z0-9_.-]", "_", host)
            written.append(self._write_compose(
                f"docker-compose.remote_{safe_host}.yml", services, remote_host=host))
        if remote:
            self._write_remote_readme(remote)
        return written

    # ------------------------------------------------------------------ #
    def _build_service(self, gname, cfg, files):
        has_cpp = any(f.get("language") == "cpp" for f in files)
        launch_file = f"{gname}_launch.py"
        ws = "/root/ros2_ws"
        launch_path = f"{ws}/src/user_project/launch/{launch_file}"

        cmd_parts = ["source /opt/ros/humble/setup.bash"]
        netem = netem_command(cfg)
        if netem:
            # iproute2 есть в osrf-образах; '|| true' чтобы не падать без tc
            cmd_parts.append(f"({netem} || echo 'netem skipped')")
        if has_cpp:
            cmd_parts.append(f"cd {ws} && colcon build --symlink-install")
            cmd_parts.append(f"source {ws}/install/setup.bash")
        cmd_parts.append(f"ros2 launch {launch_path}")
        command = "bash -c \"" + " && ".join(cmd_parts) + "\""

        service = {
            "image": cfg.get("image"),
            "container_name": f"bp_{self.pkg_name}_{gname}",
            "volumes": [f"./src:{ws}/src/user_project"],
            "environment": resolved_env(cfg),
            "command": command,
            "network_mode": cfg.get("network_mode", "host"),
            "restart": cfg.get("restart", "no"),
        }

        if cfg.get("privileged"):
            service["privileged"] = True
        if netem:
            service["cap_add"] = ["NET_ADMIN"]

        qos = (cfg.get("dds") or {}).get("qos_xml", "")
        if qos and os.path.exists(qos):
            service["volumes"].append(f"{os.path.abspath(qos)}:/etc/dds_profile.xml:ro")

        res = cfg.get("resources") or {}
        if res.get("cpus"):
            service["cpus"] = str(res["cpus"])
        if res.get("memory"):
            service["mem_limit"] = str(res["memory"])

        # bridge-сети между сервисами должны делить ROS_DOMAIN_ID — он уже в env
        return service

    # ------------------------------------------------------------------ #
    def _write_compose(self, filename, services, remote_host=None):
        doc = {"services": services}
        path = os.path.join(self.project_path, filename)
        header = "# Generated by ROS 2 Blueprint Studio v0.6.0 (deploy groups)\n"
        if remote_host:
            header += f"# Target: {remote_host}\n# Deploy: DOCKER_HOST={remote_host} docker compose -f {filename} up --build\n"
        with open(path, "w", encoding="utf-8") as f:
            f.write(header)
            yaml.dump(doc, f, sort_keys=False, default_flow_style=False, allow_unicode=True)
        return path

    def _write_remote_readme(self, remote):
        lines = [
            "# Remote deploy (v0.6.0 MVP)",
            "",
            "Для каждой удалённой машины сгенерирован отдельный compose-файл.",
            "Требования: на машине установлен Docker, у тебя SSH-доступ по ключу,",
            "обе машины в одной сети и используют один ROS_DOMAIN_ID.",
            "",
        ]
        for host in remote:
            safe_host = re.sub(r"[^a-zA-Z0-9_.-]", "_", host)
            lines += [
                f"## {host}",
                "```bash",
                f"export DOCKER_HOST={host}",
                f"docker compose -f docker-compose.remote_{safe_host}.yml up --build -d",
                "```",
                "",
            ]
        lines += [
            "> ⚠️ Не отлажено на реальном железе, пока не прогнано на двух машинах",
            "> (см. roadmap, раздел 4). Грабли: discovery между машинами, фаерволы,",
            "> SSH-ключи.",
        ]
        with open(os.path.join(self.project_path, "DEPLOY_REMOTE.md"), "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
